name: flipkart-csat-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - pandas
      - numpy
      - scikit-learn
      - joblib
      - azureml-inference-server-http
      - imbalanced-learn
      - xgboost
